prod.appPackage=com.app.smartdigibook
prod.appActive=com.app.smartdigibook.ui.activity.splash.SplashActivity
prod.userNumber=7777777733
prod.userPassword=777777
uat.appPackage= com.app.smartdigibook
uat.appActive= com.app.smartdigibook.ui.activity.splash.SplashActivity
uat.userNumber=7777777733
uat.userPassword=777777